obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[0.3, 0.3], [0.3, -0.3], [-0.3, -0.3], [-0.3,0.3 ]]
#footprint: [[0.1289, 0.34], [0.1289, -0.34], [-0.1289, -0.34], [-0.5211,-0.14 ], [-0.5211,0.14], [-0.1289, 0.34]]
footprint: [[0.325, 0.34], [0.325, -0.34], [0.0672, -0.34], [-0.325,-0.14 ], [-0.325,0.14], [0.0672, 0.34]]
inflation_radius: 0.55 #0.55
cost_scaling_factor: 10.0
transform_tolerance: 0.5
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
min_obstacle_height: 0.0
max_obstacle_height: 1.0
